---

  - name: stop tomcat server
    service: name=cocktail state=stopped #pattern=cocktail

  - name: ensure that server is stopped
    wait_for: port=8080 state=stopped delay=2 timeout=5

  - name: Install Cocktail Webapp from DropBox
    get_url: url="https://dl.dropbox.com/s/c0568sfgm285msn/cocktail.war" dest=/home/vagrant/apache-tomcat/cocktail/webapps/cocktail.war force=no

  - name: restart tomcat
    service: name=cocktail state=started

  - name: ensure that server is started
    wait_for: port=8080 state=started delay=5 timeout=10

